### ISSUE TITLE
Discord banner isn't working

### ISSUE THREAD

**Issue by bobonthenet** [AdrienQuillet/godot-yet-another-behavior-tree#18]
I'm not sure if this is the intent but when I click the discord banner it just opens the image in a new tab. I would assume this is supposed to take me to a discord server but it does not. I'm sorry if this assumption is incorrect, I would really like to reach out for questions.

**Comment by Earewien** [comment]
@bobonthenet  my bad, I omit to put discord permalink to banner 🙃
Should be fix now
You also can join using [this link](https://discord.gg/SWg6vgcw3F)

See you soon :)
