### ISSUE TITLE
Installing v3.0.0 from Asset Library tries to add the whole repository

### ISSUE THREAD

**Issue by hsandt** [AdrienQuillet/godot-yet-another-behavior-tree#29]
When installing v3.0.0 from the Asset Library, I noticed that all files and folders can be imported:

![image](https://user-images.githubusercontent.com/1067772/225703228-572affad-fdf7-447d-9758-1bf26d66eca8.png)

It's possible to uncheck some of the file/folders, but even then they will be placed widly in project root. It would be nice if files not needed in other projects were ignored, and others rearranged under addons/ or alternatively some sub-folder with a more specific name.

- root files: .gitattributes, .gitignore, LICENSE.md, README.md, project.godot: just ignore them
- documentation: ignore it, it's meant for GitHub (if you really want to distribute it then move it under addons/yet_another_behavior_tree together with the README.md/LICENSE.md)
- examples: move it under addons/yet_another_behavior_tree, or at yet_another_behavior_tree/examples, or at examples/yet_another_behavior_tree so it's not confused with other add-ons with their own examples placed at the root. Generally speaking, I'd prefer having everything under the addons sub-folder
- script_templates: this one is the standard path for Godot, so this can be kept. Besides, BTNode/ tells us what we're dealing with.

Note that I don't know how other add-ons like GUT manage to ignore files and folders. I've heard of .gdignore but GUT doesn't seem to use it, and it would only work for folders.

**Comment by Earewien** [comment]
Apparently it can be configured using `.gitattribute` file 
Should have read the documentation ~~
https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html

```
# Normalize line endings for all files that Git considers text files.
* text=auto eol=lf

# Only include the addons folder when downloading from the Asset Library.
/**        export-ignore
/addons    !export-ignore
/addons/** !export-ignore
```

**Comment by Earewien** [comment]
Should be okay now. Documentation and examples or ignored when exported from Github

**Comment by hsandt** [comment]
Thanks. Just a minor issue: LICENSE.md is still exported.

I noticed it's duplicate with the one in add-ons, but maybe you want to keep a copy at the root so it applies to examples too, and GitHub detects it properly.

In this case, you could just add it to export-ignore.

**Comment by hsandt** [comment]
I also realize the examples were quite useful, we'll have to think about a way to restore them in a clean way.

Either we keep them at the root and do not export-ignore them, but we add some sub-folder `yet_another_behavior_tree` as I suggested above. Or we move them completely under addons to follow the possibly incoming new standard where everything is under addons. I started a discussion on https://github.com/godotengine/godot-proposals/issues/554 to see what structure they prefer.

In the meantime, I'll just clone the repo and copy the examples.

**Comment by hsandt** [comment]
OK, the issue you see just above (Examples bad zoom) has a discussion containing an argument against importing the examples by default (they may not work out of the box with certain game window settings).

I'll try to discuss this further with the Godot team, as allowing standalone examples would be great.

EDIT: I opened a discussion if you're curious: https://github.com/godotengine/godot-proposals/discussions/6546
