### ISSUE TITLE
Typo in Asset Library: *Yeat* Another Behavior Tree

### ISSUE THREAD

**Issue by hsandt** [AdrienQuillet/godot-yet-another-behavior-tree#30]
The [Asset Library page](https://godotengine.org/asset-library/asset/1591) says "Yeat" instead of "Yet".

I see no typo in plugin.cfg so maybe it's something that appeared when manually registering to the Asset Library.

**Comment by Earewien** [comment]
...
I'm as good as English/proffreading as to create icons...
Change is submitted in Godot Asset Library. Thanks for submitting the issue !
