### ISSUE TITLE
Examples sometimes fail on start with error "Invalid get index 'global_position' (on base: 'Nil')"

### ISSUE THREAD

**Issue by hsandt** [AdrienQuillet/godot-yet-another-behavior-tree#31]
Sometimes, the example scenes fail with: 

> Invalid get index 'global_position' (on base: 'Nil')

due to `node` being null in:

```gd
func move_to(delta:float, node:Node2D) -> int:
	if global_position.distance_to(node.global_position) > 10:
```

It seems easy to reproduce the error by opening just a scene like player.tscn or lumberjack.tscn.

However, when opening main.tscn, behavior is erratical: sometimes I have the error, sometimes I don't.

**Comment by Earewien** [comment]
I already saw this error somewhere...

@hsandt on which addon version do you reproducde the issue ? Is that on 3.0.0 or in HEAD (latest sources) ? 

Edit : commit https://github.com/AdrienQuillet/godot-yet-another-behavior-tree/commit/8e1dc3b353576a034dc1e3117ce3af383871e287 fixed some behavior that is quite like the issue you are mentionning

**Comment by hsandt** [comment]
v3.0.0 downloaded from Asset Library.
Will try v3.1.0 now.

**Comment by hsandt** [comment]
With v3.1.0 + examples downloaded from repository main branch (should correspond to same version), I get a different error (on all examples):

> Invalid call. Nonexistent function 'append' in base 'Nil'.

in

```gd
func declare_presence(blackboard:BTBlackboard) -> int:
	blackboard.get_data("players").append(player_name)  # here
	return BTTickResult.SUCCESS
```

Apparently, players data is missing.

**Comment by Earewien** [comment]
@hsandt I reproduce your issue, but it's not a *real* one. It occurs when your directly play the *player.tscn* scene (or *lumberjack.tscn* scene, with a slitly different error). 

For every example, the *main.tscn* scene should be run. Doing it, it should work as expected. Can you check this ?

**Comment by hsandt** [comment]
I know it triggers at 100% when opening the isolated scenes yes. But for some reason after doing that, even if you open the main scenes, you can trigger the error in the main scene too.

No, wait, I got it. It's because of Godot 4 new Run Current Scene (F6) behavior: it will replay the last scene instead of the last opened scene until you Stop Running Project (F8).

I knew it was disturbing but it wasn't such an issue until now. I'll close this issue and see with the team if we can't get the old behavior as an option.
