### ISSUE TITLE
BTNode template function signature doesn't match the parent: missing return type int

### ISSUE THREAD

**Issue by hsandt** [AdrienQuillet/godot-yet-another-behavior-tree#34]
Create a new script from BTNode template immediately shows an error:

> The function signature doesn't match the parent. Parent signature is "tick(Node2D, BTBlackboard) -> int".

We just need to replace `Node2D` with `Node` and add `-> int` to the template.

However, if we do https://github.com/AdrienQuillet/godot-yet-another-behavior-tree/issues/33 before, then we'll need to add -> BTTickResult instead.

**Comment by hsandt** [comment]
(just edited message to mention Node2D -> Node too, but you'll find out quickly when testing)

**Comment by Earewien** [comment]
Obviously a regression from #11 
Don't know why, I can't see my templates in my addon Godot project... 
I will fix it (*Node2D -> Node*), the *-> int* is already present.
