### ISSUE TITLE
Not working on Godot 4.1 beta 3

### ISSUE THREAD

**Issue by TicklesTheBrain** [AdrienQuillet/godot-yet-another-behavior-tree#37]
Seems to be complaining about super._init() in the BTNode script. Perhaps a change in GDScript caused that?

**Comment by Earewien** [comment]
Hi

It's related to https://github.com/AdrienQuillet/godot-yet-another-behavior-tree/issues/36

In beta 3 they add a check since it' not allowed to do that.
I will make a new release tonight to fix that :)

For the moment you can remove the line directly in your addon sources

**Comment by Earewien** [comment]
@TicklesTheBrain is now fixed

Release is available directly on Github (https://github.com/AdrienQuillet/godot-yet-another-behavior-tree/releases/tag/3.2.0), and will soon be available on Assets Library :)
